# Generated by Django 5.0 on 2024-03-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_file_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_size',
            new_name='size',
        ),
    ]
