# Generated by Django 5.0.3 on 2024-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Hakan', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
