# Generated by Django 5.0 on 2024-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_email_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='size_left',
            field=models.IntegerField(default=15728640),
        ),
    ]
